allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // Fallback for legacy artifacts
        maven { url 'https://jitpack.io' } // For GitHub-hosted dependencies
        gradlePluginPortal()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
